version: 2.1
orbs:
  node: circleci/node@5

jobs:

  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  code-analysis:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Code analysis
          command: |
            echo "Running code analysis"

  unit-tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - run:
          command: npm install jest-junit
      - run:
          name: Run unit tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/

  integration-tests:
    executor: node/default
    steps:
      - run:
          name: Run integ tests
          command: echo "Running IT"

  prepare-deployment-environment:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Preparing deployment environment
          command: echo "Preparing deployment env"

  build-and-deploy-dev:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Deploying dev branch
          command: echo "Deploying dev branch on dev environment"

  build-and-deploy-prod:
    docker:
      - image: cimg/node:20.5.0
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Pull Vercel Environment Information
          command: sudo vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts
          command: |
            node --version
            sudo vercel build --prod --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: sudo vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

  verification-tests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run verification tests
          command: |
            echo "Running verif tests"

  load-tests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run load tests
          command: |
            echo "Running load tests"


workflows:
  build-and-test:
    jobs:
      # build
      - install-dependencies
      - code-analysis:
          requires:
            - install-dependencies

      # tests
      - unit-tests:
          requires:
            - code-analysis
      - integration-tests:
          requires:
            - unit-tests

      # deploy
      - prepare-deployment-environment:
          requires:
            - integration-tests
          filters:
            branches:
              only:
                - develop
                - main
      - build-and-deploy-dev:
          requires:
            - prepare-deployment-environment
          filters:
            branches:
              only:
                - develop
      - build-and-deploy-prod:
          requires:
            - prepare-deployment-environment
          filters:
            branches:
              only:
                - main

      # check deployed
      - verification-tests:
          requires:
            - build-and-deploy-dev
            - build-and-deploy-prod
      - load-tests:
          requires:
            - build-and-deploy-dev
            - build-and-deploy-prod
